[package]
name = "windot"
version = "0.1.0"
edition = "2021"

[package.metadata.nix]
build = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.0"
gio = "0.16.0"
gtk-layer-shell = "0.5.1"
